### ISSUE TITLE
median & quantile 

### ISSUE THREAD

**Issue by novaexe** [54rt1n/ComfyUI-DareMerge#3]
they can no longer be performed on the sum of 2 models and loaded?

**Comment by novaexe** [comment]
in addition im also very confused by the masked approach in general, as it now requires a base model to be created first?
some example workflows would be fantastic.

**Comment by 54rt1n** [comment]
The masking used to be hidden under the surface, and didn't work very well.  The purpose is to be able to find 'significant' parameters by comparing it to a base model.  For DARE-TIES merging, the mask is optional, but can be used to protect some parameters from being overwritten.  All of the options that were moved to masking were only related to that operation.

**Comment by novaexe** [comment]
hmm 🤔 so there is now no longer a way to choose? as before it was quite clear
![image](https://github.com/54rt1n/ComfyUI-DareMerge/assets/69226867/630d1052-ed2b-4678-b37f-f9bb0292941b)

**Comment by 54rt1n** [comment]
https://github.com/54rt1n/ComfyUI-DareMerge/blob/master/examples/daremerge.png Does this help?

**Comment by novaexe** [comment]
mmmm kinda but i still dont get it :(

**Comment by 54rt1n** [comment]
I added another picture.  You can see how the original model image is changed a lot when you do a normal dare merge, but when you mask the original model it retains a lot more of it's original character because it protected the 'most trained' parameters in the original model by comparing it to the base model (SD 1.5).

https://github.com/54rt1n/ComfyUI-DareMerge/blob/master/examples/daremergepic.png

**Comment by novaexe** [comment]
yea i suppose i need to play around with it more, still cant merge though quantile between just 2 merges tho?

**Comment by novaexe** [comment]
or is that what the masked model is now for? so it requires a base?

**Comment by 54rt1n** [comment]
I pushed an update and changed the wording around some.  If you wanted to do just a quantile merge without doing the dare-ties sampling, you could take and create a mask from the two models you want to merge (so you can find all the changes above/below your quantile), and then just do a regular Masked Model merge.  I think it makes more sense the more you play with it.

**Comment by novaexe** [comment]
tyvm for ur time an patience, mostly im just trying to wrap my head around where dare merge fits in? thought it would be a drop in replacement of sorts for add difference initially, turns out its way more complicated than that, as before i could merge 2 models with completely different deltas and achieve something similar, looks like that is no longer the case or my brain is having trouble understanding the masked sum of 2 parts then to target instead of the way it was before with c being the protected model and ab being a chosen difference of how much more of either you would want

**Comment by novaexe** [comment]
> hmm 🤔 so there is now no longer a way to choose? as before it was quite clear ![image](https://private-user-images.githubusercontent.com/69226867/299072221-630d1052-ed2b-4678-b37f-f9bb0292941b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTI0MzcsIm5iZiI6MTcwNjA1MjEzNywicGF0aCI6Ii82OTIyNjg2Ny8yOTkwNzIyMjEtNjMwZDEwNTItZWQyYi00Njc4LWIzN2YtZjliYjAyOTI5NDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIzMjIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZTFjOGM0NWUwNTMyNDFmMTg5YWRlYmY2NTVmZmE0ZTRiYjNmZDkzYzUzOTBlZjUwZjk1ZmIyMmYzNGVhMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ZNQwir8tLjyY0N5EGQ2_29Seywe78AiQEvWyXM3DQo)

as again this was significantly easier to understand than being forced into a repeat merge even if it was being done in the backend for you

**Comment by novaexe** [comment]
![image](https://github.com/54rt1n/ComfyUI-DareMerge/assets/69226867/04d9aeb2-d7a2-460b-b502-a1fd1ad39ca2)
as this is now what makes the most sense to me but by ur example that is incorrect

**Comment by novaexe** [comment]
![image](https://github.com/54rt1n/ComfyUI-DareMerge/assets/69226867/14bee037-4601-4691-b4d0-c9625bb1f3a1)

**Comment by 54rt1n** [comment]
The mask selects all of the parameters you want to include in the merge.  Since we don't want to overwrite the biggest ones in the model we are merging in to; we mask our target model with 'below' at ~90%.  That way those parameters we want to keep are excluded from the merge.

**Comment by 54rt1n** [comment]
The math behind the DARE-TIES is that you don't need to take all of the parameters in a merge, and if you only take some percentage of the likely best ones, the resulting model can have the full capabilities of both, instead of just capabilities 'in the middle' between two models.  You cycle your seed until you find one that captured a part of the second model you were wanting to add.

**Comment by novaexe** [comment]
so in your example that is taking the knowledge of sakura with a 90% and injecting it into dreamshaper, that part i get, what i don't is why protect dreamshaper instead of sakura

**Comment by 54rt1n** [comment]
It drops 90% of sakura's parameters and protects dreamshaper because I don't want to overwrite the parameters that are highly significant to the original model's output.

**Comment by novaexe** [comment]
oooooo okay i think i understand now! right i was kinda on the right track just got confused bu the reverse order compaired to an add difference merge A*+(b-c)

**Comment by novaexe** [comment]
in this way i guess it would be A+protect(c)+90%drop of b

**Comment by novaexe** [comment]
or something like that tyvm again! xD very interesting stuff nd just a little complicated but ill take the time to learn it :D
