### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_resetPeakMemoryStats'

### ISSUE THREAD

**Issue by a-ru2016** [54rt1n/ComfyUI-DareMerge#4]
I'm using an M1macbook, but I got an error because I don't have cuda.
/ComfyUI-DareMerge/components/dare_mbw.py", line 86, in merge
     with cuda_memory_profiler():
It worked except for with cuda_memory_profiler():, so is it possible to change it to turn off this depending on the device?

**Comment by 54rt1n** [comment]
Oof, yes I'll add a check.

**Comment by 54rt1n** [comment]
I pushed a fix, but I can't test it.  Let me know if it worked for you.

**Comment by a-ru2016** [comment]
It's done! thank you.
