### ISSUE TITLE
Insufficient memory

### ISSUE THREAD

**Issue by a-ru2016** [54rt1n/ComfyUI-DareMerge#5]
If you connect many nodes as shown in the diagram, you will run out of memory. Is it possible to clear models that are no longer needed and reload them when changes are made?
I can do this by running CLIP and UNet separately.
<img width="782" alt="スクリーンショット 2024-01-27 5 22 23" src="https://github.com/54rt1n/ComfyUI-DareMerge/assets/124528449/b6b5f13f-2d7a-4367-9faf-9d7cc66195ec">

**Comment by 54rt1n** [comment]
Yeah, I've hit the same issue on occasion.  My workaround is to save the merged checkpoint and load it again in another workflow.

**Comment by a-ru2016** [comment]
thank you. That seems like the best option after all. If there is anything else, I will create an issue.
